### PR TITLE
[WIP] Simple setup without ABC

### PR DESCRIPTION
**Pull request by betatim**
To get things going.

### CODE REVIEW

**Comment by cranmer** [comment]
I may be wrong, but I think this change was to modify the "true" value of `theta` not `phi`. I'm looking at `simulator(3.1, phi, n_samples=10000)` and 3.1 vs 3.14 is the theta value.

**Comment by cranmer** [comment]
it would be nice to have example use emcee (or something similar) to get posterior theta samples.

also, entropy should be calculated for the distribution of theta. It looks like it's being calculated on a distribution over x 
`entropy(Distribution(simulator(3.1, phi, n_samples=10000)).probabilities, d1.probabilities)`

**Comment by betatim** [comment]
Thanks for the comments and the short skype. God knows what confused state I would have ended up in otherwise.

I think, fingerscrossed, that the additions to `active-sciencing.ipynb` make sense.

Still a bit of a mess to be sorted out but at least now the EIG curve doesn't depend on the `phi` you chose when collecting the first round of data.

**Comment by cranmer** [comment]
That's great!

But can I confirm that you mean "doesn't depend on theta" ? The curve is EIG(phi) vs. phi, so it clearly depends on phi. I think you mean the most sensitive experimental settings phi don't depend on the true value of the Gaussian mean theta.

**Comment by betatim** [comment]
What I meant is that the best setting in terms of phi doesn't depend on the value of phi you used to collect the data set that particular iteration starts from. It is a total no brainer that this should be true, which is why I was so puzzled in one of the earlier attempts.

Not explicitly checked against the value of theta. Probably a nice plot to add.

**Pull request merged**
