### PR TITLE
Use a KDE to estimate the MAP

### LINKED ISSUE #11: distribution: MAP from KDE or just from sample histogram
If MAP from histogram, depends strongly on binning. becomes an issue, if binning too fine for statistics available for posterior (directly related to how much time we want to spend in emcee)

screenshot

### PR DESCRIPTION
**Pull request by betatim**
Fixes #11, waiting for notebook to finish executing, then ready for merge.

### CODE REVIEW

**Comment by betatim** [comment]
Also sets `n_calls` to ten (fix #12)

**Comment by betatim** [comment]
Can be merged. Though it seems the approximate likelihood get's us in trouble at the moment :-/

**Comment by betatim** [comment]
Rerunning the notebook with a much larger number of samples from the simulator to build the PDF in the emcee likelihood.

**Comment by betatim** [comment]
Ok, notebook is still running after an hour so probably ok to merge as is.

**Comment by cranmer** [comment]
Integrated this change manually

**Pull request closed without merging**
