### PR TITLE
[MRG] Fix init of walkers, KDE for prior and some plots

### PR DESCRIPTION
**Pull request by betatim**
This is a branch to experiment around on.

### CODE REVIEW

**Comment by betatim** [comment]
I think the reason emcee get's stuck is because we initialise the walkers somewhere where the prior is zero.

**Comment by betatim** [comment]
The diff is hard to read, as always with a notebook. The important code changes are at the top, at the end I added some new plots and tidied up what looked like old plotting/experimenting.

**Comment by cranmer** [comment]
thanks!

**Comment by cranmer** [comment]
Could you move the `Distribution` class into a separate python file and have subplots that show the EIG[phi] vs. phi for each iteration?

**Comment by cranmer** [comment]
perhaps some dotted lines for true theta and optimal phi

**Pull request merged**
